templateapp/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = 'template_app'
urlpatterns = [
  path('', views.index, name='index'),
  path('/home/<first_name>/<last_name>', views.home, name='home'),
  path('/sample1', views.sample1, name='sample1'),
  path('/sample2', views.sample2, name='sample2'),
  path('/sample3', views.sample3, name='sample3'),
  path('/sample', views.sample, name='sample')
]

udemy_template/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('template_app', include('templateapp.urls')),
]

templateapp/models.py
from django.db import models

# Create your models here.

templateapp/views.py
from django.http import request
from django.shortcuts import render, resolve_url

# Create your views here.
def index (request):
  val = 'Goodbye'
  return render(request, 'index.html', context={'value':val})

def home (request, first_name, last_name):
  my_name = f'{first_name} {last_name}'
  favorite_fruits = ['Apple','Grape','Lemon']
  my_info = {
    'name':'Taro',
    'age' : 18
  }
  status = 20
  return render(request, 'home.html', context = {
    'my_name' : my_name,
    'favorite_fruits' : favorite_fruits,
    'my_info' : my_info,
    'status': status
  })

def sample1(request):
  return render(request, 'sample1.html')

def sample2(request):
  return render(request, 'sample2.html')

def sample(request):
  name = 'ichiro yamada'
  height = 175.5
  weight = 72
  bmi = weight / (height/100)**2
  page_url = 'ホームページ: https://github.com/bonot9434'
  favorite_fruits = [
    'Apple','Grape','Lemon'
  ]
  msg = """hello
  my name is
  ichiro"""
  msg2 = '1234567890'
  return render(request, 'sample.html', context={
    'name' : name,
    'bmi' : bmi,
    'page_url' : page_url,
    'fruits' : favorite_fruits,
    'msg' : msg,
    'msg2' : msg2
  })

class Country:
  def __init__(self, name, population, capital):
      self.name = name
      self.population = population
      self.capital = capital
def sample3(request):
    country = Country('Japan', 100000000, 'Tokyo')
    return render(request, 'sample3.html', context={
      'country': country
    })

templateapp/templates/index.html
<h1>Hello</h1>

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>{% block title %}My Page{% endblock %}</title>
  </head>
  <body>
    <h1>My Page</h1>
    {% block content %}{% endblock %}
  </body>
</html>

templates/home.html
{% load event_tags %}
{% comment %} <h1>Name: {{my_name}}</h1>
<h2>果物：{{favorite_fruits.2}}</h2>
<h3>Age: {{my_info.age}}</h3> {% endcomment %}
{{ my_name }}

{# for #}
<ul>
  {% for fruit in favorite_fruits %}
    <li>{{fruit}}</li>
  {% endfor %}
</ul>

{# if #}
{% if 'Grap' in favorite_fruits %}
  <p>Grapeあります</p>
{% elif 'Lemo' in favorite_fruits %}
  <p>Lemonあります</p>
{% else %}
  <p>Not Found</p>
{% endif %}

{% if 'age' in my_info %}
  <p>age in my_info</p>
    {% if my_info.age < 20 %}
      <p>未成年</p>
    {% endif %}
{% endif %}

{% if my_info.name != 'Taro' %}
  <p>Taroでない</p>
{% endif %}

<p>{{ status | status_to_string:'AAA' }}</p>

templates/index.html
<h1>index</h1>
<p>{{ value }}</p>

templates/sample.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'download/home.css' %}">

<h1>{{ name }}</h1>
<h1>{{ page_url | urlize}}</h1>
<p>BMI: {{ bmi | floatformat:2 }}</p>
<p>給料: {{ salary | default:'秘密' }}</p>
<p>{{ fruits | random | lower }}</p>
<p>{{ fruits | join:', ' }}</p>
<p>{{ msg | linebreaks }}</p>
<p>{{ msg2 | truncatechars:7}}</p>

{% filter upper %}
<p>aaa</p>
<h1>bbb</h1>
{% endfilter %}

<a href="{% url 'template_app:home' first_name='Saburo' last_name='Konishi' %}">home</a>

<img src="{% static 'download/sample.jpg' %}">

templates/sample1.html
{% extends "base.html" %}
{% block title %}Sample1 {{ block.super }}{% endblock %}
{% block content %}
  <p>Sample1</p>
{% endblock %}

templates/sample2.html
{% extends "base.html" %}
{% block title %}Sample2 {{ block.super }}{% endblock %}
{% block content %}
  <p>Sample2</p>
{% endblock %}

templates/sample3.html
国名: {{ country.name }}<br>
人口: {{ country.population }}<br>
首都: {{ country.capital }}